### ISSUE TITLE
Boilerplate suggestion

### ISSUE THREAD

**Issue by longnt80** [lvnam96/Notflix#1]
I suggest we use this boilerplate:

https://github.com/react-boilerplate/react-boilerplate

**Comment by lvnam96** [comment]
I think it's not necessary. This is just a small project for the purpose of practicing :wink:
I implemented it in the project in my local repo yesterday, but still not see anything good for us yet!

Can you tell me what advantages we'll have if we use it?

**Comment by longnt80** [comment]
After doing some research, I think we can write our own.

Let's start with basic webpack config first.
